### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [gleydson/AmbassadorOfArcadia#14]
Hi

Just came across your project, I am a logo designer who also loves to use my logo design skills to help contribute to open source projects, I want to help create a LOGO for your project...

I am working on some idea concepts already to represent your project... I will post it here once I am done so you can give me your feedback on any adjustment you may want...

Regards...

**Comment by gleydson** [comment]
@chimzycash Hi, how cool! This project is the development of an application for children who have autism, it would be very interesting to help, because it is a project of completion of course.

This is a game that aims to help children who have autism to integrate into society by helping psychologists in their treatment.

The game has an environment oriented towards spatial elements like planets and stars, including the main characters are ETs.

Maybe this will help inspire you!

Thanks in advance!

**Comment by chimzycash** [comment]
Cool... was waiting for your reply... I would work on an idea concept and will update it here for your feedback

**Comment by chimzycash** [comment]
Ok... Great name... while i am working on it, might be cool to ask about the age range of children that will use the app

**Comment by gleydson** [comment]
@chimzycash 8~11

**Comment by chimzycash** [comment]
Ok... great

**Comment by gleydson** [comment]
Oh my God, man, it was really cool! I liked it very much, I think the concept is very consistent with the project proposal, I really liked it.

About color, in the design I use a lot of elements in color rgb(143,98,145). But the colors you chose were very good.

Anyway, you're a great design!

**Comment by chimzycash** [comment]
![logo design_aoa_background_icon 223](https://user-images.githubusercontent.com/37814297/50727508-0577bb00-111c-11e9-86b2-e8ed4e054627.jpg)

Here is the updated one with colors from the app

**Comment by chimzycash** [comment]
The files are ready, I will prepare the files with the vector files and Png and create a PULL REQUEST...

**Comment by gleydson** [comment]
Wonderful! I want to thank you for your spectacular work. I am very happy with the result, thank you very much for your incredible contribution. :heart:

**Comment by chimzycash** [comment]
Thanks! we can communicate via Discord

**Comment by gleydson** [comment]
Cool, my Discord is `gleydsonsr`

**Comment by chimzycash** [comment]
Nice... Will send you a message

**Comment by chimzycash** [comment]
can't seem to find you.

**Comment by gleydson** [comment]
Try this `DomNegronne`

**Comment by chimzycash** [comment]
Not showing up... Maybe you can send the number username #tag

**Comment by chimzycash** [comment]
Hi...
Here is the Google Drive Link for the files including the vector files for your use.
https://drive.google.com/drive/folders/1sMtZibH60b-NJJ0wZXuROA96Lvid3nJR?usp=sharing

You can reach me on discord if anything is needed. My Discord is chimzycash#8304

**Comment by gleydson** [comment]
Wonderful, I sent you an invitation on the discord
